"""Import legacy GammaLedger v2.5 JSON exports into the SQL database.

Accepts both shapes documented in DOMAIN_MODEL_MAP §1:
  - File export: { version, exportDate, trades, mcpContext }
  - localStorage envelope: { version, timestamp, fileName, trades, mcpContext }

Applies the `tradeReasoning -> notes` field rename (DOMAIN_MODEL_MAP §8) and
strips runtime fields (RUNTIME_TRADE_FIELDS) since they're recomputed.

mcpContext is intentionally NOT imported — it's regenerated by the analytics
domain in Phase 2+.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, cast
from uuid import uuid4

from anyio import Path as AsyncPath
from sqlmodel import col, select
from sqlmodel.ext.asyncio.session import AsyncSession

from ..domains.pnl.calculations import calculate_pl, from_dict, from_orm, total_fees
from ..domains.settings.models import (
    ApiCredentialConfig,
    AppSetting,
    ConsentRecord,
    LegacyImportBatch,
    LegImportMetadata,
    TradeRuntimeSnapshot,
)
from ..domains.trades import service
from ..domains.trades.models import Trade
from ..domains.trades.schemas import TradeCreate

# Set of trade-level keys to drop before validation (RUNTIME_TRADE_FIELDS,
# DOMAIN_MODEL_MAP §2). These appear in saved JSON because the legacy app
# writes them back so the MCP server can read pre-computed metrics.
_RUNTIME_TRADE_FIELDS = frozenset(
    {
        "legsCount",
        "openContracts",
        "closeContracts",
        "openLegs",
        "rollLegs",
        "totalFees",
        "totalDebit",
        "totalCredit",
        "cashFlow",
        "capitalAtRisk",
        "fees",
        "primaryLeg",
        "tradeType",
        "tradeDirection",
        "quantity",
        "strikePrice",
        "multiplier",
        "displayStrike",
        "activeStrikePrice",
        "entryPrice",
        "exitPrice",
        "pmccShortExpiration",
        "longExpirationDate",
        "entryDate",
        "exitDate",
        "pl",
        "roi",
        "maxRisk",
        "maxRiskLabel",
        "riskIsUnlimited",
        "lifecycleMeta",
        "lifecycleStatus",
        "partialClose",
        "rolledForward",
        "autoExpired",
        "daysHeld",
        "dte",
        "weeklyROI",
        "monthlyROI",
        "annualizedROI",
        "tradeReasoning",
        "wheelCoverage",
        "shares",
        "effectiveCostBasis",
        "marketValue",
        "unrealizedPL",
        "marketPriceSource",
        "marketPriceSnapshot",
    }
)

_RUNTIME_LEG_FIELDS = frozenset(
    {"externalId", "importGroupId", "importSource", "importBatchId", "tickerSymbol"}
)


@dataclass
class ImportResult:
    imported: int
    replaced: int
    skipped: int
    errors: list[str]
    source_trade_count: int
    persisted_trade_count: int
    source_leg_count: int
    persisted_leg_count: int
    source_financial_checksum: float
    persisted_financial_checksum: float
    import_batch_id: str
    runtime_snapshots: int
    leg_metadata_rows: int
    settings_rows: int


def _runtime_trade_fields(raw: dict[str, Any]) -> dict[str, Any]:
    return {k: raw[k] for k in _RUNTIME_TRADE_FIELDS if k in raw}


def _runtime_leg_fields(raw: dict[str, Any]) -> dict[str, Any]:
    return {k: raw[k] for k in _RUNTIME_LEG_FIELDS if k in raw}


def _normalize_trade(raw: dict[str, Any]) -> dict[str, Any]:
    """Strip runtime fields and apply the tradeReasoning → notes rename."""
    out = {k: v for k, v in raw.items() if k not in _RUNTIME_TRADE_FIELDS}

    # tradeReasoning → notes (DOMAIN_MODEL_MAP §8)
    if raw.get("tradeReasoning") and not out.get("notes"):
        out["notes"] = raw["tradeReasoning"]

    out["legs"] = [
        {k: v for k, v in leg.items() if k not in _RUNTIME_LEG_FIELDS}
        for leg in raw.get("legs", [])
    ]
    return out


def _parse_payload(payload: str | list[Any] | dict[str, Any]) -> Any:
    return json.loads(payload) if isinstance(payload, str) else payload


def parse_export(payload: str | list[Any] | dict[str, Any]) -> list[dict[str, Any]]:
    """Parse a v2.5 JSON export and return normalized trade dicts.

    Tolerates the bare-array legacy shape too (LEGACY_STORAGE_KEYS values)."""
    data: Any = _parse_payload(payload)
    if isinstance(data, list):
        # Legacy shape: a bare trades[] array
        trades = data
    elif isinstance(data, dict) and isinstance(data.get("trades"), list):
        trades = data["trades"]
    else:
        raise ValueError("not a recognised GammaLedger export — missing trades[]")
    normalized = []
    for item in trades:
        if not isinstance(item, dict):
            raise ValueError("not a recognised GammaLedger export — trades[] must contain objects")
        normalized.append(_normalize_trade(cast(dict[str, Any], item)))
    return normalized


async def import_export(
    session: AsyncSession,
    payload: str | list[Any] | dict[str, Any],
    *,
    replace_existing: bool = True,
    user_id: str = "local",
    tenant_id: str | None = None,
) -> ImportResult:
    """Read a v2.5 JSON export and persist trades. Existing trades with the
    same id are replaced when replace_existing=True (default), else skipped."""
    data = _parse_payload(payload)
    raw_trades = _extract_raw_trades(data)
    trades = [_normalize_trade(raw) for raw in raw_trades]
    imported = 0
    replaced = 0
    skipped = 0
    errors: list[str] = []
    source_trade_count = len(trades)
    source_leg_count = sum(len(raw.get("legs", [])) for raw in trades)
    source_financial_checksum = _source_financial_checksum(trades)
    touched_ids: list[str] = []
    batch_id = f"legacy-{uuid4().hex}"
    leg_metadata_rows = 0

    session.add(
        _build_import_batch(
            batch_id=batch_id,
            user_id=user_id,
            data=data,
            source_trade_count=source_trade_count,
            source_leg_count=source_leg_count,
            source_financial_checksum=source_financial_checksum,
        )
    )

    for raw_original, raw in zip(raw_trades, trades, strict=True):
        try:
            trade_payload = TradeCreate.model_validate(raw)
        except Exception as exc:  # pragma: no cover — surfaces in error list
            errors.append(f"{raw.get('id', '<no id>')}: {exc}")
            continue

        existing = await service.get_trade_or_none(
            session, trade_payload.id, user_id=user_id, tenant_id=tenant_id
        )
        if existing is not None:
            if not replace_existing:
                skipped += 1
                continue
            await service.upsert_trade(
                session, trade_payload, user_id=user_id, tenant_id=tenant_id
            )
            replaced += 1
            touched_ids.append(trade_payload.id)
            leg_metadata_rows += await _preserve_legacy_trade_surface(
                session, batch_id=batch_id, raw=raw_original
            )
        else:
            await service.create_trade(
                session, trade_payload, user_id=user_id, tenant_id=tenant_id
            )
            imported += 1
            touched_ids.append(trade_payload.id)
            leg_metadata_rows += await _preserve_legacy_trade_surface(
                session, batch_id=batch_id, raw=raw_original
            )

    settings_rows = await _preserve_settings(session, data)

    await session.flush()
    persisted = await _persisted_validation(
        session, touched_ids, user_id=user_id, tenant_id=tenant_id
    )
    runtime_snapshots = len(
        (
            await session.exec(
                select(TradeRuntimeSnapshot).where(
                    col(TradeRuntimeSnapshot.trade_id).in_(touched_ids)
                )
            )
        ).all()
    )

    return ImportResult(
        imported=imported,
        replaced=replaced,
        skipped=skipped,
        errors=errors,
        source_trade_count=source_trade_count,
        persisted_trade_count=persisted["trade_count"],
        source_leg_count=source_leg_count,
        persisted_leg_count=persisted["leg_count"],
        source_financial_checksum=source_financial_checksum,
        persisted_financial_checksum=persisted["financial_checksum"],
        import_batch_id=batch_id,
        runtime_snapshots=runtime_snapshots,
        leg_metadata_rows=leg_metadata_rows,
        settings_rows=settings_rows,
    )


def _trade_model() -> Any:
    # Import lazily to avoid circular imports at module load.
    from ..domains.trades.models import Trade

    return Trade


async def import_file(
    session: AsyncSession,
    path: str | Path,
    *,
    replace_existing: bool = True,
    user_id: str = "local",
    tenant_id: str | None = None,
) -> ImportResult:
    text = await AsyncPath(path).read_text(encoding="utf-8")
    return await import_export(
        session, text, replace_existing=replace_existing, user_id=user_id, tenant_id=tenant_id
    )


def _extract_raw_trades(data: Any) -> list[dict[str, Any]]:
    if isinstance(data, list):
        trades = data
    elif isinstance(data, dict) and isinstance(data.get("trades"), list):
        trades = data["trades"]
    else:
        raise ValueError("not a recognised GammaLedger export — missing trades[]")
    normalized = []
    for item in trades:
        if not isinstance(item, dict):
            raise ValueError("not a recognised GammaLedger export — trades[] must contain objects")
        normalized.append(cast(dict[str, Any], item))
    return normalized


def _build_import_batch(
    *,
    batch_id: str,
    user_id: str,
    data: Any,
    source_trade_count: int,
    source_leg_count: int,
    source_financial_checksum: float,
) -> LegacyImportBatch:
    envelope = data if isinstance(data, dict) else {}
    return LegacyImportBatch(
        id=batch_id,
        user_id=user_id,
        source_version=_str_or_none(envelope.get("version")),
        export_date=_dt_or_none(envelope.get("exportDate")),
        timestamp=_dt_or_none(envelope.get("timestamp")),
        file_name=_str_or_none(envelope.get("fileName")),
        source_shape="bare_trades_array" if isinstance(data, list) else "export_envelope",
        mcp_context=envelope.get("mcpContext")
        if isinstance(envelope.get("mcpContext"), dict)
        else None,
        source_trade_count=source_trade_count,
        source_leg_count=source_leg_count,
        source_financial_checksum=source_financial_checksum,
    )


async def _preserve_legacy_trade_surface(
    session: AsyncSession, *, batch_id: str, raw: dict[str, Any]
) -> int:
    leg_metadata_rows = 0
    runtime = _runtime_trade_fields(raw)
    if runtime:
        existing_runtime = await session.get(TradeRuntimeSnapshot, raw["id"])
        if existing_runtime is not None:
            await session.delete(existing_runtime)
            await session.flush()
        session.add(TradeRuntimeSnapshot(trade_id=raw["id"], fields=runtime))

    for leg in raw.get("legs", []):
        if not isinstance(leg, dict) or "id" not in leg:
            continue
        metadata = _runtime_leg_fields(leg)
        if not metadata:
            continue
        existing_meta = await session.get(LegImportMetadata, leg["id"])
        if existing_meta is not None:
            await session.delete(existing_meta)
            await session.flush()
        session.add(
            LegImportMetadata(
                leg_id=str(leg["id"]),
                external_id=_str_or_none(leg.get("externalId")),
                import_group_id=_str_or_none(leg.get("importGroupId")),
                import_source=_str_or_none(leg.get("importSource")),
                import_batch_id=_str_or_none(leg.get("importBatchId")) or batch_id,
                ticker_symbol=_str_or_none(leg.get("tickerSymbol")),
                raw=metadata,
            )
        )
        leg_metadata_rows += 1
    return leg_metadata_rows


async def _preserve_settings(session: AsyncSession, data: Any) -> int:
    if not isinstance(data, dict):
        return 0
    rows = 0
    rows += await _upsert_api_config(session, service="gemini", data=data)
    rows += await _upsert_api_config(session, service="finnhub", data=data)
    rows += await _upsert_consent(
        session, "GammaLedgerDisclaimerAcceptedAt", data.get("GammaLedgerDisclaimerAcceptedAt")
    )
    rows += await _upsert_consent(
        session, "GammaLedgerAICoachConsentAt", data.get("GammaLedgerAICoachConsentAt")
    )
    for key in ("GammaLedgerSidebarCollapsed", "GammaLedgerDefaultFeePerContract"):
        if key in data:
            await _upsert_setting(session, key, {"value": data[key]})
            rows += 1
    return rows


async def _upsert_api_config(session: AsyncSession, *, service: str, data: dict[str, Any]) -> int:
    if service == "gemini":
        config_key = "GammaLedgerGeminiConfig"
        secret_key = "GammaLedgerGeminiSecret"
        tokens_key = "GammaLedgerGeminiMaxTokens"
        rate_key = None
    else:
        config_key = "GammaLedgerFinnhubConfig"
        secret_key = "GammaLedgerFinnhubSecret"
        tokens_key = None
        rate_key = "GammaLedgerFinnhubRateLimit"
    raw_config = data.get(config_key)
    if (
        raw_config is None
        and data.get(secret_key) is None
        and (rate_key is None or data.get(rate_key) is None)
    ):
        return 0
    config_data = raw_config if isinstance(raw_config, dict) else {}
    existing = await session.get(ApiCredentialConfig, service)
    if existing is not None:
        await session.delete(existing)
        await session.flush()
    session.add(
        ApiCredentialConfig(
            service=service,
            model=_str_or_none(config_data.get("model")),
            encrypted=bool(config_data.get("enc")),
            payload=config_data.get("payload")
            if isinstance(config_data.get("payload"), dict)
            else None,
            fallback=_str_or_none(config_data.get("fallback")),
            secret_material=_str_or_none(data.get(secret_key)),
            max_tokens=_int_or_none(data.get(tokens_key)) if tokens_key else None,
            rate_limit_per_minute=_int_or_none(data.get(rate_key)) if rate_key else None,
            migrated_plaintext_present=bool(config_data.get("apiKey")),
        )
    )
    return 1


async def _upsert_consent(session: AsyncSession, key: str, value: Any) -> int:
    accepted_at = _dt_or_none(value)
    if accepted_at is None:
        return 0
    existing = await session.get(ConsentRecord, key)
    if existing is not None:
        await session.delete(existing)
        await session.flush()
    session.add(ConsentRecord(key=key, accepted_at=accepted_at))
    return 1


async def _upsert_setting(session: AsyncSession, key: str, value: dict[str, Any]) -> None:
    existing = await session.get(AppSetting, key)
    if existing is not None:
        await session.delete(existing)
        await session.flush()
    session.add(AppSetting(key=key, value=value))


def _source_financial_checksum(trades: list[dict[str, Any]]) -> float:
    checksum = 0.0
    for trade in trades:
        legs = [from_dict(leg) for leg in trade.get("legs", [])]
        checksum += calculate_pl(legs)
        checksum += total_fees(legs)
    return round(checksum, 2)


async def _persisted_validation(
    session: AsyncSession, trade_ids: list[str], *, user_id: str, tenant_id: str | None = None
) -> dict[str, Any]:
    if not trade_ids:
        return {"trade_count": 0, "leg_count": 0, "financial_checksum": 0.0}
    statement = select(Trade).where(
        Trade.id.in_(trade_ids),  # type: ignore[attr-defined]
        Trade.user_id == user_id,
    )
    if tenant_id is not None:
        statement = statement.where(Trade.tenant_id == tenant_id)
    rows = (await session.exec(statement)).all()
    leg_count = 0
    checksum = 0.0
    for trade in rows:
        legs = [from_orm(leg) for leg in trade.legs]
        leg_count += len(legs)
        checksum += calculate_pl(legs)
        checksum += total_fees(legs)
    return {
        "trade_count": len(rows),
        "leg_count": leg_count,
        "financial_checksum": round(checksum, 2),
    }


def _str_or_none(value: Any) -> str | None:
    return None if value in (None, "") else str(value)


def _int_or_none(value: Any) -> int | None:
    if value in (None, ""):
        return None
    return int(value)


def _dt_or_none(value: Any) -> datetime | None:
    if value in (None, ""):
        return None
    if isinstance(value, datetime):
        return value
    if isinstance(value, str):
        return datetime.fromisoformat(value.replace("Z", "+00:00")).replace(tzinfo=None)
    return None
